site_name: Kalavai Docs
nav:
  - Home: index.md
  - Develop: developers.md
  - Share your device: hosts.md
  - FAQs: faqs.md

theme:
  name: material
  navigation_depth: 3
  logo: assets/icons/logo_no_background.png
  favicon: assets/icons/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  